### ISSUE TITLE
Trusted Client Incompatible issue, tried different streamer ALVR versions but no success

### ISSUE THREAD

**Issue by timhubpie** [alvr-org/alvr-visionos#100]
Great job and I'm almost there.

Error message '...Ecpected protocol ID: 1686...7063, found 7466...5457' 

Tried different versions (20.4, 20.5, 20.6., 21.0.0). No success.

**Comment by timhubpie** [comment]
Fixed by itself, have no idea why it works now..

**Comment by Utopiah** [comment]
I have the same problem so please open back this issue, cf

![2024-03-26-120844_963x838_scrot](https://github.com/alvr-org/alvr-visionos/assets/1076655/59ea16ef-41c7-47ed-b039-208b8360fef1)

using the latest AppImage so ALVR v20.6.1.

**Comment by timhubpie** [comment]
Reopen on request. Version 21.0.0 nightly does work here. As I wrote had the issue before but now is working.

**Comment by shinyquagsire23** [comment]
I thiiiiink I've more or less resolved this with the new UI, which shows the client's version and protocol version. In the future if the client breaks protocol version I plan on showing a little "What's New?" dialogue box thing so that there's at least some kind of noticable indication that the streamer needs updating

**Comment by huuck** [comment]
Still happening, and there is absolutely no way to figure out which client to use with your server.
